# Build the base image rootfs:alpine-3.9.3
from scratch

# Requires to put a rootfs in this directory so that
# docker daemon can unpack and build the initial image.
# Rootfs can be obtained from alpine linux site.
ADD alpine-minirootfs-3.9.3-x86_64.tar /
